import type { RewardTask } from "./types"

const MINUTE_MS = 60 * 1000
const HOUR_MS = 60 * MINUTE_MS
const DAY_MS = 24 * HOUR_MS

export function buildDefaultRewardsCatalog(now = Date.now()): RewardTask[] {
  return [
    // —— New users: onboarding sandbox checklist ——
    {
      id: "connect-wallet",
      category: "new_user",
      tag: "setup",
      title: "Boot your sandbox wallet",
      description: "Your Avana session is live — this quest unlocks automatically when you land.",
      rewardAmount: 25,
      rewardSymbol: "AVA",
      actionLabel: "Connected",
      actionKind: "auto",
      requirement: { type: "event_count", eventTypes: ["wallet_connected"], targetCount: 1 },
      repeatable: false,
    },
    {
      id: "create-profile",
      category: "new_user",
      tag: "setup",
      title: "Spin up your profile",
      description: "We create a demo wallet profile so every product sandbox shares the same session.",
      rewardAmount: 20,
      rewardSymbol: "AVA",
      actionLabel: "Ready",
      actionKind: "auto",
      requirement: { type: "profile_completed", targetCount: 1 },
      repeatable: false,
    },
    {
      id: "review-risk-basics",
      category: "new_user",
      tag: "education",
      title: "Read the sandbox risk primer",
      description: "Open the 60-second LP risk briefing before you simulate any position.",
      rewardAmount: 15,
      rewardSymbol: "AVA",
      actionLabel: "Read primer",
      actionKind: "education_modal",
      requirement: { type: "education_completed", targetCount: 1 },
      repeatable: false,
    },
    {
      id: "favorite-market",
      category: "new_user",
      tag: "setup",
      title: "Pin a market to your watchlist",
      description: "Pick one Borrow, Lend, or Multiply market to track in your sandbox.",
      rewardAmount: 10,
      rewardSymbol: "AVA",
      actionLabel: "Pick market",
      actionKind: "favorite_modal",
      requirement: { type: "event_count", eventTypes: ["market_favorited"], targetCount: 1 },
      repeatable: false,
    },
    {
      id: "run-first-simulation",
      category: "new_user",
      tag: "simulation",
      title: "Preview your first trade",
      description: "Run a real sandbox preview on Borrow, Lend, or Multiply — no funds move.",
      rewardAmount: 20,
      rewardSymbol: "AVA",
      actionLabel: "Preview",
      actionKind: "simulate_modal",
      requirement: { type: "event_count", eventTypes: ["simulation_created"], targetCount: 1 },
      repeatable: false,
    },
    {
      id: "first-lend-deposit",
      category: "new_user",
      tag: "lend",
      title: "Make your first sandbox lend",
      description: "Deposit into any Lend market. Your live session records the quest automatically.",
      rewardAmount: 40,
      rewardSymbol: "AVA",
      actionLabel: "Go to Lend",
      actionKind: "deep_link",
      requirement: { type: "event_count", eventTypes: ["lend_deposited"], targetCount: 1, product: "lend" },
      repeatable: false,
    },
    {
      id: "first-borrow",
      category: "new_user",
      tag: "borrow",
      title: "Open your first sandbox borrow",
      description: "Borrow against LP collateral on the Borrow page — the quest completes on success.",
      rewardAmount: 50,
      rewardSymbol: "AVA",
      actionLabel: "Go to Borrow",
      actionKind: "deep_link",
      requirement: { type: "event_count", eventTypes: ["borrow_opened"], targetCount: 1, product: "borrow" },
      repeatable: false,
    },
    {
      id: "first-multiply",
      category: "new_user",
      tag: "multiply",
      title: "Open your first sandbox multiply",
      description: "Create a Multiply position in the sandbox and let the session bridge log it.",
      rewardAmount: 60,
      rewardSymbol: "AVA",
      actionLabel: "Go to Multiply",
      actionKind: "deep_link",
      requirement: { type: "event_count", eventTypes: ["multiply_opened"], targetCount: 1, product: "multiply" },
      repeatable: false,
    },
    {
      id: "first-repay",
      category: "new_user",
      tag: "borrow",
      title: "Repay a sandbox loan",
      description: "Repay any borrow position you opened — a healthy loop in the demo world.",
      rewardAmount: 25,
      rewardSymbol: "AVA",
      actionLabel: "Repay on Borrow",
      actionKind: "deep_link",
      requirement: { type: "event_count", eventTypes: ["borrow_repaid"], targetCount: 1, product: "borrow" },
      repeatable: false,
    },
    {
      id: "first-deleverage",
      category: "new_user",
      tag: "multiply",
      title: "Deleverage a sandbox position",
      description: "Reduce any Multiply position to practice risk management.",
      rewardAmount: 35,
      rewardSymbol: "AVA",
      actionLabel: "Deleverage",
      actionKind: "deep_link",
      requirement: { type: "event_count", eventTypes: ["multiply_deleveraged"], targetCount: 1, product: "multiply" },
      repeatable: false,
    },
    {
      id: "first-reward-claim",
      category: "new_user",
      tag: "rewards",
      title: "Claim your first AVA reward",
      description: "Complete any other quest, then claim it to unlock this milestone.",
      rewardAmount: 30,
      rewardSymbol: "AVA",
      actionLabel: "Claim",
      actionKind: "product_action",
      requirement: { type: "event_count", eventTypes: ["reward_claimed"], targetCount: 1, product: "rewards" },
      repeatable: false,
    },
    {
      id: "maintain-safe-account",
      category: "new_user",
      tag: "risk",
      title: "Sandbox cool-down",
      description: "Explore Avana for 2 minutes after your first login, then come back to claim.",
      rewardAmount: 50,
      rewardSymbol: "AVA",
      actionLabel: "Waiting",
      actionKind: "wait_timer",
      requirement: { type: "wait_since_login", waitMs: 2 * MINUTE_MS },
      repeatable: false,
    },

    // —— Challenge tasks: sandbox achievements ——
    {
      id: "supply-5k-lend",
      category: "challenge",
      tag: "volume",
      title: "Lend $500 in the sandbox",
      description: "Stack sandbox lend deposits until you reach $500 supplied.",
      rewardAmount: 100,
      rewardSymbol: "AVA",
      actionLabel: "Lend more",
      actionKind: "deep_link",
      requirement: { type: "aggregate_volume", eventTypes: ["lend_deposited"], targetUsd: 500 },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "borrow-2k",
      category: "challenge",
      tag: "volume",
      title: "Borrow $200 in the sandbox",
      description: "Open borrow positions totaling $200 across any collateral pool.",
      rewardAmount: 120,
      rewardSymbol: "AVA",
      actionLabel: "Borrow more",
      actionKind: "deep_link",
      requirement: { type: "aggregate_volume", eventTypes: ["borrow_opened"], targetUsd: 200 },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "open-2x-multiply",
      category: "challenge",
      tag: "multiply",
      title: "Launch a multiply position",
      description: "Open any Multiply position in the sandbox — size is up to you.",
      rewardAmount: 90,
      rewardSymbol: "AVA",
      actionLabel: "Multiply",
      actionKind: "deep_link",
      requirement: { type: "event_count", eventTypes: ["multiply_opened"], targetCount: 1 },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "use-3-products",
      category: "challenge",
      tag: "product",
      title: "Tour all three products",
      description: "Complete one action in Lend, Borrow, and Multiply.",
      rewardAmount: 150,
      rewardSymbol: "AVA",
      actionLabel: "Explore",
      actionKind: "product_action",
      requirement: {
        type: "event_count",
        eventTypes: ["lend_deposited", "borrow_opened", "multiply_opened"],
        targetCount: 3,
        distinctProducts: ["lend", "borrow", "multiply"],
      },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "use-curve-position",
      category: "challenge",
      tag: "integration",
      title: "Curve sandbox tour",
      description: "Visit the Curve-style borrow market tour and mark it complete.",
      rewardAmount: 80,
      rewardSymbol: "AVA",
      actionLabel: "Start tour",
      actionKind: "sandbox_tour",
      requirement: {
        type: "event_count",
        eventTypes: ["sandbox_tour_completed"],
        targetCount: 1,
        marketId: "curve-sandbox-tour",
      },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "use-uniswap-v4-position",
      category: "challenge",
      tag: "integration",
      title: "Uniswap v4 sandbox tour",
      description: "Walk through the Uniswap v4 sandbox market and check it off.",
      rewardAmount: 80,
      rewardSymbol: "AVA",
      actionLabel: "Start tour",
      actionKind: "sandbox_tour",
      requirement: {
        type: "event_count",
        eventTypes: ["sandbox_tour_completed"],
        targetCount: 1,
        marketId: "uniswap-v4-sandbox-tour",
      },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "maintain-hf-above-2",
      category: "challenge",
      tag: "risk",
      title: "Risk check-in (5 min)",
      description: "Stay in the sandbox for 5 minutes after login, then claim this patience badge.",
      rewardAmount: 110,
      rewardSymbol: "AVA",
      actionLabel: "Waiting",
      actionKind: "wait_timer",
      requirement: { type: "wait_since_login", waitMs: 5 * MINUTE_MS },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "keep-multiply-safe",
      category: "challenge",
      tag: "risk",
      title: "Multiply mindfulness (3 min)",
      description: "Take a 3-minute breather after login before claiming this calm-multiply quest.",
      rewardAmount: 110,
      rewardSymbol: "AVA",
      actionLabel: "Waiting",
      actionKind: "wait_timer",
      requirement: { type: "wait_since_login", waitMs: 3 * MINUTE_MS },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "complete-5-borrow-repay-cycles",
      category: "challenge",
      tag: "activity",
      title: "3 borrow / repay loops",
      description: "Repay sandbox loans three times to practice healthy borrow cycles.",
      rewardAmount: 95,
      rewardSymbol: "AVA",
      actionLabel: "Repay",
      actionKind: "deep_link",
      requirement: { type: "event_count", eventTypes: ["borrow_repaid"], targetCount: 3, product: "borrow" },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "complete-3-multiply-deleverage-cycles",
      category: "challenge",
      tag: "activity",
      title: "2 deleverage drills",
      description: "Deleverage Multiply positions twice to complete this risk drill.",
      rewardAmount: 105,
      rewardSymbol: "AVA",
      actionLabel: "Deleverage",
      actionKind: "deep_link",
      requirement: { type: "event_count", eventTypes: ["multiply_deleveraged"], targetCount: 2, product: "multiply" },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "activate-5-markets",
      category: "challenge",
      tag: "mastery",
      title: "Explore 3 sandbox markets",
      description: "Complete tours on three different market pages across Avana.",
      rewardAmount: 130,
      rewardSymbol: "AVA",
      actionLabel: "Explore",
      actionKind: "sandbox_tour",
      requirement: { type: "event_count", eventTypes: ["sandbox_tour_completed"], targetCount: 3 },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "claim-rewards-5-times",
      category: "challenge",
      tag: "rewards",
      title: "Claim 3 quest rewards",
      description: "Claim AVA from three separate quests to build your rewards streak.",
      rewardAmount: 80,
      rewardSymbol: "AVA",
      actionLabel: "Claim",
      actionKind: "product_action",
      requirement: { type: "event_count", eventTypes: ["reward_claimed"], targetCount: 3, product: "rewards" },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "4-week-activity-streak",
      category: "challenge",
      tag: "streak",
      title: "3-day sandbox streak",
      description: "Check in on three separate days after your first login.",
      rewardAmount: 140,
      rewardSymbol: "AVA",
      actionLabel: "Check in",
      actionKind: "product_action",
      requirement: { type: "streak", eventTypes: ["daily_checkin"], targetCount: 3, interval: "day" },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "grow-portfolio-10k",
      category: "challenge",
      tag: "volume",
      title: "Grow sandbox portfolio by $1K",
      description: "Lend, borrow, or multiply until your combined sandbox volume hits $1,000.",
      rewardAmount: 180,
      rewardSymbol: "AVA",
      actionLabel: "Grow",
      actionKind: "product_action",
      requirement: {
        type: "aggregate_volume",
        eventTypes: ["lend_deposited", "borrow_opened", "multiply_opened"],
        targetUsd: 1_000,
      },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "open-8-active-positions",
      category: "challenge",
      tag: "mastery",
      title: "Open 3 sandbox positions",
      description: "Hold three open positions across Lend, Borrow, or Multiply.",
      rewardAmount: 220,
      rewardSymbol: "AVA",
      actionLabel: "Open",
      actionKind: "product_action",
      requirement: {
        type: "event_count",
        eventTypes: ["lend_deposited", "borrow_opened", "multiply_opened"],
        targetCount: 3,
        distinctMarketIds: true,
      },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },

    // —— Referral tasks: sandbox social loop ——
    {
      id: "share-referral-link",
      category: "referral",
      tag: "referral",
      title: "Copy your sandbox invite link",
      description: "Generate and copy a referral link you can share with friends.",
      rewardAmount: 15,
      rewardSymbol: "AVA",
      actionLabel: "Copy link",
      actionKind: "copy_referral",
      requirement: { type: "event_count", eventTypes: ["referral_link_created"], targetCount: 1, product: "referral" },
      repeatable: false,
    },
    {
      id: "invite-first-wallet",
      category: "referral",
      tag: "referral",
      title: "Send your first sandbox invite",
      description: "Simulate inviting a friend wallet into your Avana sandbox crew.",
      rewardAmount: 40,
      rewardSymbol: "AVA",
      actionLabel: "Send invite",
      actionKind: "sandbox_referral_invite",
      requirement: { type: "referral_count", eventTypes: ["referral_connected"], targetCount: 1 },
      repeatable: false,
    },
    {
      id: "first-funded-referral",
      category: "referral",
      tag: "referral",
      title: "Fund a referred sandbox wallet",
      description: "Mark one invited friend as funded after they try a product action.",
      rewardAmount: 70,
      rewardSymbol: "AVA",
      actionLabel: "Mark funded",
      actionKind: "sandbox_referral_fund",
      requirement: { type: "referral_count", eventTypes: ["referral_funded"], targetCount: 1 },
      repeatable: false,
    },
    {
      id: "bring-3-active-users",
      category: "referral",
      tag: "referral",
      title: "Activate 3 sandbox friends",
      description: "Three referred wallets complete a product action in your sandbox network.",
      rewardAmount: 140,
      rewardSymbol: "AVA",
      actionLabel: "Activate",
      actionKind: "sandbox_referral_activate",
      requirement: { type: "referral_count", eventTypes: ["referral_activated"], targetCount: 3 },
      repeatable: false,
    },
    {
      id: "bring-5-active-users",
      category: "referral",
      tag: "referral",
      title: "Grow crew to 5 actives",
      description: "Five referred wallets complete a product action in your sandbox network.",
      rewardAmount: 220,
      rewardSymbol: "AVA",
      actionLabel: "Grow crew",
      actionKind: "sandbox_referral_activate",
      requirement: { type: "referral_count", eventTypes: ["referral_activated"], targetCount: 5 },
      repeatable: false,
    },
    {
      id: "referral-cohort-25k",
      category: "referral",
      tag: "volume",
      title: "Referral sandbox hits $500",
      description: "Your referred crew reaches $500 in combined sandbox volume.",
      rewardAmount: 260,
      rewardSymbol: "AVA",
      actionLabel: "Boost crew",
      actionKind: "sandbox_referral_fund",
      requirement: { type: "aggregate_volume", eventTypes: ["referral_funded"], targetUsd: 500 },
      repeatable: false,
    },
    {
      id: "referral-streak",
      category: "referral",
      tag: "streak",
      title: "Referral streak (2 activations)",
      description: "Activate two sandbox referrals to keep your invite momentum going.",
      rewardAmount: 240,
      rewardSymbol: "AVA",
      actionLabel: "Continue",
      actionKind: "sandbox_referral_activate",
      requirement: { type: "referral_count", eventTypes: ["referral_activated"], targetCount: 2 },
      repeatable: false,
    },
    {
      id: "avana-ambassador",
      category: "referral",
      tag: "referral",
      title: "Sandbox ambassador",
      description: "Activate five friends in your sandbox referral network.",
      rewardAmount: 400,
      rewardSymbol: "AVA",
      actionLabel: "Ambassador",
      actionKind: "sandbox_referral_activate",
      requirement: { type: "referral_count", eventTypes: ["referral_activated"], targetCount: 5 },
      repeatable: false,
    },
  ]
}

export const REWARD_TASK_DEEP_LINKS: Record<string, string> = {
  "first-lend-deposit": "/lend",
  "first-borrow": "/borrow",
  "first-multiply": "/multiply",
  "first-repay": "/borrow",
  "first-deleverage": "/multiply",
  "use-3-products": "/lend",
  "claim-rewards-5-times": "/dashboard",
  "grow-portfolio-10k": "/lend",
  "open-8-active-positions": "/lend",
  "supply-5k-lend": "/lend",
  "borrow-2k": "/borrow",
  "open-2x-multiply": "/multiply",
  "complete-5-borrow-repay-cycles": "/borrow",
  "complete-3-multiply-deleverage-cycles": "/multiply",
}

export const REWARD_SANDBOX_TOURS: Record<string, { marketId: string; href: string; label: string }> = {
  "use-curve-position": { marketId: "curve-sandbox-tour", href: "/borrow", label: "Curve sandbox" },
  "use-uniswap-v4-position": { marketId: "uniswap-v4-sandbox-tour", href: "/borrow", label: "Uniswap v4 sandbox" },
  "activate-5-markets": { marketId: "market-tour", href: "/lend", label: "Lend markets" },
}
