import type { RewardTask } from "./types"

const DAY_MS = 24 * 60 * 60 * 1000

export function buildDefaultRewardsCatalog(now = Date.UTC(2026, 5, 19)): RewardTask[] {
  return [
    {
      id: "connect-wallet",
      category: "new_user",
      tag: "setup",
      title: "Connect your wallet",
      description: "Connect a wallet and start an Avana session.",
      rewardAmount: 25,
      rewardSymbol: "AVA",
      actionLabel: "Connect",
      requirement: { type: "event_count", eventTypes: ["wallet_connected"], targetCount: 1 },
      repeatable: false,
    },
    {
      id: "create-profile",
      category: "new_user",
      tag: "setup",
      title: "Create Avana profile",
      description: "Complete basic profile preferences.",
      rewardAmount: 20,
      rewardSymbol: "AVA",
      actionLabel: "Finish setup",
      requirement: { type: "profile_completed", targetCount: 1 },
      repeatable: false,
    },
    {
      id: "review-risk-basics",
      category: "new_user",
      tag: "education",
      title: "Review risk basics",
      description: "Read the Avana risk primer.",
      rewardAmount: 15,
      rewardSymbol: "AVA",
      actionLabel: "Read",
      requirement: { type: "education_completed", targetCount: 1 },
      repeatable: false,
    },
    {
      id: "favorite-market",
      category: "new_user",
      tag: "setup",
      title: "Favorite a market",
      description: "Save one Borrow, Lend, or Multiply market.",
      rewardAmount: 10,
      rewardSymbol: "AVA",
      actionLabel: "Favorite",
      requirement: { type: "event_count", eventTypes: ["market_favorited"], targetCount: 1 },
      repeatable: false,
    },
    {
      id: "run-first-simulation",
      category: "new_user",
      tag: "simulation",
      title: "Run your first simulation",
      description: "Preview a Borrow, Lend, or Multiply action.",
      rewardAmount: 20,
      rewardSymbol: "AVA",
      actionLabel: "Simulate",
      requirement: { type: "event_count", eventTypes: ["simulation_created"], targetCount: 1 },
      repeatable: false,
    },
    {
      id: "first-lend-deposit",
      category: "new_user",
      tag: "lend",
      title: "Make your first lend deposit",
      description: "Deposit into any supported Lend market.",
      rewardAmount: 40,
      rewardSymbol: "AVA",
      actionLabel: "Lend",
      requirement: { type: "event_count", eventTypes: ["lend_deposited"], targetCount: 1, product: "lend" },
      repeatable: false,
    },
    {
      id: "first-borrow",
      category: "new_user",
      tag: "borrow",
      title: "Open your first borrow",
      description: "Borrow against supported LP collateral.",
      rewardAmount: 50,
      rewardSymbol: "AVA",
      actionLabel: "Borrow",
      requirement: { type: "event_count", eventTypes: ["borrow_opened"], targetCount: 1, product: "borrow" },
      repeatable: false,
    },
    {
      id: "first-multiply",
      category: "new_user",
      tag: "multiply",
      title: "Open your first multiply",
      description: "Create one Multiply position.",
      rewardAmount: 60,
      rewardSymbol: "AVA",
      actionLabel: "Multiply",
      requirement: { type: "event_count", eventTypes: ["multiply_opened"], targetCount: 1, product: "multiply" },
      repeatable: false,
    },
    {
      id: "first-repay",
      category: "new_user",
      tag: "borrow",
      title: "Complete your first repay",
      description: "Repay any active borrow position.",
      rewardAmount: 25,
      rewardSymbol: "AVA",
      actionLabel: "Repay",
      requirement: { type: "event_count", eventTypes: ["borrow_repaid"], targetCount: 1, product: "borrow" },
      repeatable: false,
    },
    {
      id: "first-deleverage",
      category: "new_user",
      tag: "multiply",
      title: "Complete your first deleverage",
      description: "Reduce one Multiply position.",
      rewardAmount: 35,
      rewardSymbol: "AVA",
      actionLabel: "Deleverage",
      requirement: { type: "event_count", eventTypes: ["multiply_deleveraged"], targetCount: 1, product: "multiply" },
      repeatable: false,
    },
    {
      id: "first-reward-claim",
      category: "new_user",
      tag: "rewards",
      title: "Claim your first reward",
      description: "Claim any completed task reward.",
      rewardAmount: 30,
      rewardSymbol: "AVA",
      actionLabel: "Claim",
      requirement: { type: "event_count", eventTypes: ["reward_claimed"], targetCount: 1, product: "rewards" },
      repeatable: false,
    },
    {
      id: "maintain-safe-account",
      category: "new_user",
      tag: "risk",
      title: "Maintain safe account",
      description: "Keep positions above the safety threshold for 7 days.",
      rewardAmount: 50,
      rewardSymbol: "AVA",
      actionLabel: "Monitor",
      requirement: { type: "holding_period", eventTypes: ["borrow_position_healthy", "multiply_safe_period_completed"], targetCount: 1, durationDays: 7 },
      repeatable: false,
    },
    {
      id: "supply-5k-lend",
      category: "challenge",
      tag: "volume",
      title: "Supply $5K through Lend",
      description: "Reach $5,000 supplied across Lend markets.",
      rewardAmount: 100,
      rewardSymbol: "AVA",
      actionLabel: "Lend",
      requirement: { type: "aggregate_volume", eventTypes: ["lend_deposited"], targetUsd: 5_000 },
      expiresAt: now + 14 * DAY_MS,
      repeatable: false,
    },
    {
      id: "borrow-2k",
      category: "challenge",
      tag: "volume",
      title: "Borrow $2K with LP collateral",
      description: "Reach $2,000 borrowed value.",
      rewardAmount: 120,
      rewardSymbol: "AVA",
      actionLabel: "Borrow",
      requirement: { type: "aggregate_volume", eventTypes: ["borrow_opened"], targetUsd: 2_000 },
      expiresAt: now + 14 * DAY_MS,
      repeatable: false,
    },
    {
      id: "open-2x-multiply",
      category: "challenge",
      tag: "multiply",
      title: "Open a 2x Multiply position",
      description: "Create one Multiply position at 2x or higher.",
      rewardAmount: 90,
      rewardSymbol: "AVA",
      actionLabel: "Multiply",
      requirement: { type: "event_count", eventTypes: ["multiply_opened"], targetCount: 1, minAmountUsd: 2_000 },
      expiresAt: now + 14 * DAY_MS,
      repeatable: false,
    },
    {
      id: "use-3-products",
      category: "challenge",
      tag: "product",
      title: "Use 3 Avana products",
      description: "Complete one action in Borrow, Multiply, and Lend.",
      rewardAmount: 150,
      rewardSymbol: "AVA",
      actionLabel: "Explore",
      requirement: {
        type: "event_count",
        eventTypes: ["lend_deposited", "borrow_opened", "multiply_opened"],
        targetCount: 3,
        distinctProducts: ["lend", "borrow", "multiply"],
      },
      expiresAt: now + 21 * DAY_MS,
      repeatable: false,
    },
    {
      id: "use-curve-position",
      category: "challenge",
      tag: "integration",
      title: "Use a Curve LP position",
      description: "Borrow against one Curve-origin LP.",
      rewardAmount: 80,
      rewardSymbol: "AVA",
      actionLabel: "Use Curve",
      requirement: { type: "event_count", eventTypes: ["curve_lp_used"], targetCount: 1 },
      expiresAt: now + 21 * DAY_MS,
      repeatable: false,
    },
    {
      id: "use-uniswap-v4-position",
      category: "challenge",
      tag: "integration",
      title: "Use a Uniswap v4 LP position",
      description: "Borrow against one Uniswap v4 LP.",
      rewardAmount: 80,
      rewardSymbol: "AVA",
      actionLabel: "Use Uniswap",
      requirement: { type: "event_count", eventTypes: ["uniswap_v4_lp_used"], targetCount: 1 },
      expiresAt: now + 21 * DAY_MS,
      repeatable: false,
    },
    {
      id: "maintain-hf-above-2",
      category: "challenge",
      tag: "risk",
      title: "Maintain HF above 2.0",
      description: "Keep Borrow positions above 2.0 HF for 14 days.",
      rewardAmount: 110,
      rewardSymbol: "AVA",
      actionLabel: "Monitor",
      requirement: { type: "holding_period", eventTypes: ["borrow_position_healthy"], targetCount: 1, durationDays: 14 },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "keep-multiply-safe",
      category: "challenge",
      tag: "risk",
      title: "Keep Multiply safe",
      description: "Keep Multiply safe for 14 days.",
      rewardAmount: 110,
      rewardSymbol: "AVA",
      actionLabel: "Monitor",
      requirement: { type: "holding_period", eventTypes: ["multiply_safe_period_completed"], targetCount: 1, durationDays: 14 },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "complete-5-borrow-repay-cycles",
      category: "challenge",
      tag: "activity",
      title: "Complete 5 borrow/repay cycles",
      description: "Complete 5 healthy borrow/repay cycles.",
      rewardAmount: 95,
      rewardSymbol: "AVA",
      actionLabel: "Cycle",
      requirement: { type: "event_count", eventTypes: ["borrow_repaid"], targetCount: 5, product: "borrow" },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "complete-3-multiply-deleverage-cycles",
      category: "challenge",
      tag: "activity",
      title: "Complete 3 multiply/deleverage cycles",
      description: "Complete 3 Multiply risk-management cycles.",
      rewardAmount: 105,
      rewardSymbol: "AVA",
      actionLabel: "Manage risk",
      requirement: { type: "event_count", eventTypes: ["multiply_deleveraged"], targetCount: 3, product: "multiply" },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "activate-5-markets",
      category: "challenge",
      tag: "mastery",
      title: "Activate 5 markets",
      description: "Use five distinct Avana markets.",
      rewardAmount: 130,
      rewardSymbol: "AVA",
      actionLabel: "Explore",
      requirement: { type: "event_count", eventTypes: ["lend_deposited", "borrow_opened", "multiply_opened"], targetCount: 5 },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "claim-rewards-5-times",
      category: "challenge",
      tag: "rewards",
      title: "Claim rewards 5 times",
      description: "Claim rewards across five completed tasks.",
      rewardAmount: 80,
      rewardSymbol: "AVA",
      actionLabel: "Claim",
      requirement: { type: "event_count", eventTypes: ["reward_claimed"], targetCount: 5, product: "rewards" },
      expiresAt: now + 30 * DAY_MS,
      repeatable: false,
    },
    {
      id: "4-week-activity-streak",
      category: "challenge",
      tag: "streak",
      title: "4-week activity streak",
      description: "Complete one Avana action per week for four weeks.",
      rewardAmount: 140,
      rewardSymbol: "AVA",
      actionLabel: "Continue",
      requirement: { type: "streak", eventTypes: ["lend_deposited", "borrow_opened", "multiply_opened", "borrow_repaid", "multiply_deleveraged"], targetCount: 4, interval: "week" },
      expiresAt: now + 35 * DAY_MS,
      repeatable: false,
    },
    {
      id: "grow-portfolio-10k",
      category: "challenge",
      tag: "volume",
      title: "Grow portfolio by $10K",
      description: "Increase managed value by $10K.",
      rewardAmount: 180,
      rewardSymbol: "AVA",
      actionLabel: "Grow",
      requirement: { type: "aggregate_volume", eventTypes: ["lend_deposited", "borrow_opened", "multiply_opened"], targetUsd: 10_000 },
      expiresAt: now + 45 * DAY_MS,
      repeatable: false,
    },
    {
      id: "open-8-active-positions",
      category: "challenge",
      tag: "mastery",
      title: "Open 8 active positions",
      description: "Hold eight active positions across Avana products.",
      rewardAmount: 220,
      rewardSymbol: "AVA",
      actionLabel: "Open",
      requirement: { type: "event_count", eventTypes: ["lend_deposited", "borrow_opened", "multiply_opened"], targetCount: 8 },
      expiresAt: now + 45 * DAY_MS,
      repeatable: false,
    },
    {
      id: "share-referral-link",
      category: "referral",
      tag: "referral",
      title: "Share referral link",
      description: "Generate and copy a referral link.",
      rewardAmount: 15,
      rewardSymbol: "AVA",
      actionLabel: "Copy",
      requirement: { type: "event_count", eventTypes: ["referral_link_created"], targetCount: 1, product: "referral" },
      repeatable: false,
    },
    {
      id: "invite-first-wallet",
      category: "referral",
      tag: "referral",
      title: "Invite your first wallet",
      description: "A referred wallet connects and creates a profile.",
      rewardAmount: 40,
      rewardSymbol: "AVA",
      actionLabel: "Invite",
      requirement: { type: "referral_count", eventTypes: ["referral_connected"], targetCount: 1 },
      repeatable: false,
    },
    {
      id: "first-funded-referral",
      category: "referral",
      tag: "referral",
      title: "First funded referral",
      description: "One referral completes Lend, Borrow, or Multiply.",
      rewardAmount: 70,
      rewardSymbol: "AVA",
      actionLabel: "Track",
      requirement: { type: "referral_count", eventTypes: ["referral_funded"], targetCount: 1 },
      repeatable: false,
    },
    {
      id: "bring-3-active-users",
      category: "referral",
      tag: "referral",
      title: "Bring 3 active users",
      description: "Three referrals complete one product action.",
      rewardAmount: 140,
      rewardSymbol: "AVA",
      actionLabel: "Grow",
      requirement: { type: "referral_count", eventTypes: ["referral_activated"], targetCount: 3 },
      repeatable: false,
    },
    {
      id: "bring-5-active-users",
      category: "referral",
      tag: "referral",
      title: "Bring 5 active users",
      description: "Five referrals complete one product action.",
      rewardAmount: 220,
      rewardSymbol: "AVA",
      actionLabel: "Invite",
      requirement: { type: "referral_count", eventTypes: ["referral_activated"], targetCount: 5 },
      repeatable: false,
    },
    {
      id: "referral-cohort-25k",
      category: "referral",
      tag: "volume",
      title: "Referral cohort reaches $25K",
      description: "Referred users reach $25K in total managed value.",
      rewardAmount: 260,
      rewardSymbol: "AVA",
      actionLabel: "View",
      requirement: { type: "aggregate_volume", eventTypes: ["referral_funded"], targetUsd: 25_000 },
      repeatable: false,
    },
    {
      id: "referral-streak",
      category: "referral",
      tag: "streak",
      title: "Referral streak",
      description: "One new active referral per week for four weeks.",
      rewardAmount: 240,
      rewardSymbol: "AVA",
      actionLabel: "Continue",
      requirement: { type: "streak", eventTypes: ["referral_activated"], targetCount: 4, interval: "week" },
      repeatable: false,
    },
    {
      id: "avana-ambassador",
      category: "referral",
      tag: "referral",
      title: "Avana ambassador",
      description: "Reach 10 active referred wallets.",
      rewardAmount: 400,
      rewardSymbol: "AVA",
      actionLabel: "Apply",
      requirement: { type: "referral_count", eventTypes: ["referral_activated"], targetCount: 10 },
      repeatable: false,
    },
  ]
}
