const LOCAL_ASSET_ICON_SLUGS: Record<string, string> = {
  USDC: "usdc",
  USDT: "usdt",
  DAI: "dai",
  ETH: "eth",
  WETH: "weth",
  BTC: "btc",
  WBTC: "wbtc",
  CBBTC: "cbbtc",
  STETH: "steth",
  WSTETH: "wsteth",
  SOL: "sol",
  ARB: "arb",
  OP: "op",
  GHO: "gho",
  USDE: "usde",
  "3CRV": "3crv",
  CRVUSD: "crv",
  CRV: "crv",
  FRAX: "frax",
  EURC: "eurc",
  SDAI: "sdai",
  RETH: "reth",
  CBETH: "cbeth",
  WEETH: "weeth",
  AAVE: "aave",
  UNI: "uni",
  LDO: "ldo",
  BAL: "bal",
  GNO: "gno",
  AURA: "aura",
  AERO: "aero",
  DEGEN: "degen",
  BRETT: "brett",
  WELL: "well",
  "USD+": "usd-plus",
  POLYGON: "polygon",
  MATIC: "polygon",
  BASE: "base",
  BNB: "bnb",
  BLAST: "blast",
  WORLD: "world",
  "WORLD CHAIN": "world",
  AVALANCHE: "avalanche",
  AVAX: "avalanche",
  ZORA: "zora",
  LIDO: "ldo",
  PANCAKESWAP: "pancakeswap",
  "CONVEX FINANCE": "convex",
  "ROCKET POOL": "rocket-pool",
  COMPOUND: "compound",
  CHAINLINK: "chainlink",
  SUSHISWAP: "sushiswap",
  FRXUSD: "frxusd",
  USDG: "usdg",
  RLUSD: "rlusd",
}

export function getLocalAssetIcon(key: string) {
  const normalized = key.trim().toUpperCase()
  const slug = LOCAL_ASSET_ICON_SLUGS[normalized]
  return slug ? `/asset-icons/${slug}.svg` : "/placeholder.svg"
}
