import { registryIconPath } from "@/app/lib/tokens/registry"

const LOCAL_ASSET_ICON_SLUGS: Record<string, string> = {
  AVA: "ava",
  USDC: "usdc",
  USDT: "usdt",
  DAI: "dai",
  ETH: "eth",
  WETH: "weth",
  BTC: "btc",
  WBTC: "wbtc",
  CBBTC: "cbbtc",
  STETH: "steth",
  WSTETH: "wsteth",
  SOL: "sol",
  ARB: "arb",
  OP: "op",
  GHO: "gho",
  USDE: "usde",
  "3CRV": "3crv",
  CRVUSD: "crvusd",
  CRV: "crv",
  FRAX: "frax",
  EURC: "eurc",
  SDAI: "sdai",
  RETH: "reth",
  CBETH: "cbeth",
  WEETH: "weeth",
  AAVE: "aave",
  UNI: "uni",
  LDO: "ldo",
  BAL: "bal",
  GNO: "gno",
  AURA: "aura",
  AERO: "aero",
  DEGEN: "degen",
  BRETT: "brett",
  WELL: "well",
  "USD+": "usd-plus",
  POLYGON: "polygon",
  MATIC: "polygon",
  BASE: "base",
  BNB: "bnb",
  BLAST: "blast",
  WORLD: "world",
  "WORLD CHAIN": "world",
  AVALANCHE: "avalanche",
  AVAX: "avalanche",
  ZORA: "zora",
  LIDO: "ldo",
  PANCAKESWAP: "pancakeswap",
  "CONVEX FINANCE": "convex",
  "ROCKET POOL": "rocket-pool",
  COMPOUND: "compound",
  CHAINLINK: "chainlink",
  LINK: "chainlink",
  SUSHISWAP: "sushiswap",
  FRXUSD: "frxusd",
  USDG: "usdg",
  RLUSD: "rlusd",
}

/** Neutral local token placeholder used when a symbol has no mapped icon. */
export const LOCAL_ASSET_ICON_FALLBACK = "/asset-icons/placeholder.png"

export function getLocalAssetIcon(key: string) {
  const normalized = key.trim().toUpperCase()
  // New tokens (stocks, …) declare a full icon path in the token registry — prefer it.
  const registryIcon = registryIconPath(normalized)
  if (registryIcon) return registryIcon
  const slug = LOCAL_ASSET_ICON_SLUGS[normalized]
  // Always resolve to a real local file so an unmapped symbol shows a neutral
  // token placeholder instead of triggering a 404 for the missing icon.
  return slug ? `/asset-icons/${slug}.png` : LOCAL_ASSET_ICON_FALLBACK
}

/** Widths generated by scripts/generate-icon-variants.mjs, ascending. */
export const LOCAL_ICON_VARIANT_WIDTHS = [64, 96, 128] as const
const LOCAL_ICON_PNG = /^\/(asset-icons|stock-Icons)\/([^/]+)\.png$/

/**
 * The smallest generated WebP variant that covers a `cssPx` slot at 2× density, for a local
 * `/asset-icons/*.png` or `/stock-Icons/*.png` URL. The source PNGs are 128px and render
 * unoptimized, so a 16–48px icon otherwise downloads the full-size PNG. Other URLs pass through.
 */
export function sizedLocalIconSrc(src: string, cssPx: number): string {
  const match = LOCAL_ICON_PNG.exec(src)
  if (!match) return src
  const width =
    LOCAL_ICON_VARIANT_WIDTHS.find((candidate) => candidate >= cssPx * 2) ??
    LOCAL_ICON_VARIANT_WIDTHS[LOCAL_ICON_VARIANT_WIDTHS.length - 1]
  return `/${match[1]}/w${width}/${match[2]}.webp`
}
